### ISSUE TITLE
3.3.0 breaking changes with Carthage

### ISSUE THREAD

**Issue by edfanhouse** [RxSwiftCommunity/RxOptional#50]
Hi,

The last version, 3.3.0, includes breaking changes with RxSwift 4.0 implementation resulting an error when we launch a "carthage update" if we use RxSwift 3.6 in the project.

To according to Semantic Versioning, the version should be 4.0.0 ?

**Comment by freak4pc** [comment]
Yup. That’s absolutely true ... not sure who made a minor patch for RxSwift 4.0 but that wrong. If no one pushes a PR to fix this I can take care of it in a few hours.

**Comment by bobgodwinx** [comment]
@edfanhouse  `To according to Semantic Versioning, the version should be 4.0.0 ?` No because according to [semantic versioning](http://semver.org/) it should be `3.4.0` it was an update to work with `RxSwift 4.0` nothing else when it's a patch it will be `3.3.1` However we are updating the rule soon on versioning. here is the [discussion](https://github.com/RxSwiftCommunity/Action/issues/115#issuecomment-337882155)
